// AUTO-GENERATED by src/app/custom-i18n/scripts/split-i18n.mjs — do not edit.
export type LocaleId = 'zh' | 'en' | 'de';

export type TranslationKey =
  | 'demo.title'
  | 'demo.subtitle'
  | 'demo.welcome'
  | 'demo.intro'
  | 'demo.items'
  | 'demo.currentLanguage'
  | 'demo.date'
  | 'demo.number'
  | 'demo.tip'
  | 'demo.renders'
  | 'demo.editor.title'
  | 'demo.editor.file'
  | 'demo.editor.hint'
  | 'demo.editor.apply'
  | 'demo.editor.reset'
  | 'demo.editor.download'
  | 'demo.editor.valid'
  | 'demo.editor.invalid'
  | 'demo.editor.keys';

export type TranslationMap = Partial<Record<TranslationKey, string>>;

export type MergedTranslations = {
  $languages?: LocaleId[];
} & { [K in TranslationKey]?: Partial<Record<LocaleId, string>> };
