// AUTO-GENERATED by src/app/custom-i18n/scripts/split-i18n.mjs — do not edit.
import type { TranslationKey } from './i18n-keys';

export const SOURCE_MESSAGES: Record<TranslationKey, () => string> = {
  'demo.title': () => $localize`:@@demo.title:Angular Native i18n Demo`,
  'demo.subtitle': () => $localize`:@@demo.subtitle:Built with @angular/localize · runtime $localize + loadTranslations`,
  'demo.welcome': () => $localize`:@@demo.welcome:Hello, ${'{$USER}'}:USER:!`,
  'demo.intro': () => $localize`:@@demo.intro:This is a live demo of Angular's built-in i18n. Click a language button on the left to switch instantly without rebuilding, or edit the JSON config in the editor and press Apply.`,
  'demo.items': () => $localize`:@@demo.items:You have ${'{$COUNT}'}:COUNT: items in your cart`,
  'demo.currentLanguage': () => $localize`:@@demo.currentLanguage:Current language`,
  'demo.date': () => $localize`:@@demo.date:Localized date`,
  'demo.number': () => $localize`:@@demo.number:Localized number`,
  'demo.tip': () => $localize`:@@demo.tip:Tip: $localize in TS and i18n attributes in templates both support runtime translation via loadTranslations.`,
  'demo.renders': () => $localize`:@@demo.renders:Component rebuilds`,
  'demo.editor.title': () => $localize`:@@demo.editor.title:Edit Language Config`,
  'demo.editor.file': () => $localize`:@@demo.editor.file:Config file`,
  'demo.editor.hint': () => $localize`:@@demo.editor.hint:Edit the merged translations.json, check the languages and click Apply; the selection is exported on Download for the local split script.`,
  'demo.editor.apply': () => $localize`:@@demo.editor.apply:Apply`,
  'demo.editor.reset': () => $localize`:@@demo.editor.reset:Reset`,
  'demo.editor.download': () => $localize`:@@demo.editor.download:Download`,
  'demo.editor.valid': () => $localize`:@@demo.editor.valid:Applied · {N} keys`,
  'demo.editor.invalid': () => $localize`:@@demo.editor.invalid:JSON parse error:`,
  'demo.editor.keys': () => $localize`:@@demo.editor.keys:{N} translation keys`,
};
