// AUTO-GENERATED by i18n split-i18n.mjs — do not edit.
export type LocaleId = 'zh' | 'en' | 'de';

export type TranslationKey =
  | 'demo.title'
  | 'demo.subtitle'
  | 'demo.welcome'
  | 'demo.intro'
  | 'demo.items'
  | 'demo.currentLanguage'
  | 'demo.date'
  | 'demo.number'
  | 'demo.currency'
  | 'demo.tip'
  | 'demo.renders'
  | 'i18n.editor.title'
  | 'i18n.editor.file'
  | 'i18n.editor.hint'
  | 'i18n.editor.apply'
  | 'i18n.editor.reset'
  | 'i18n.editor.download'
  | 'i18n.editor.valid'
  | 'i18n.editor.invalid'
  | 'i18n.editor.keys'
  | 'ct.hero.title'
  | 'ct.hero.sub'
  | 'ct.step1.title'
  | 'ct.step1.desc'
  | 'ct.step2.title'
  | 'ct.step2.desc'
  | 'ct.step3.title'
  | 'ct.step3.desc'
  | 'ct.step4.title'
  | 'ct.step4.desc'
  | 'ct.step5.title'
  | 'ct.step5.desc'
  | 'ct.extract.title'
  | 'ct.translated.title'
  | 'ct.translated.note'
  | 'ct.xlf.error'
  | 'shell.nav.home'
  | 'shell.nav.official'
  | 'shell.nav.compile'
  | 'shell.nav.custom'
  | 'shell.lang.label'
  | 'home.official.tag'
  | 'home.official.sub'
  | 'home.compile.tag'
  | 'home.compile.sub'
  | 'home.custom.tag'
  | 'home.custom.sub';

export type TranslationMap = Partial<Record<TranslationKey, string>>;

export type MergedTranslations = {
  $languages?: LocaleId[];
} & { [K in TranslationKey]?: Partial<Record<LocaleId, string>> };
